### ISSUE TITLE
CMake: SINGLE_LANGUAGE is not very flexible

### ISSUE THREAD

**Issue by BrianSidebotham** [KiCad/kicad-doc#155]
The **SINGLE_LANGUAGE** option is not very flexible. It would be better to have an option that is a list of languages which defaults to all languages.

So, I propose we remove the **SINGLE_LANGUAGE** option and instead have a **LANGUAGES** option. To most people building a single language this will just mean reconfiguring with `-DLANGUAGES=en` instead of `-DSINGLE_LANGUAGE=en` but it does mean that any number of languages could be built, or excluded from a build. e.g `-DLANGUAGES=en;fr`

I see this as a pretty low-priority task at the moment, but it would be good to tidy the option up.

**Comment by nickoe** [comment]
Yes, indeed, I think a LANGUAGES option is more flexible.

**Comment by ciampix** [comment]
Agree

**Comment by nickoe** [comment]
Fixed by pr #567
