### ISSUE TITLE
remove FAQ section from getting_started_in_kicad

### ISSUE THREAD

**Issue by kinichiro** [KiCad/kicad-doc#164]
section 10.1 of GSiK should be removed,
since FAQ link http://www.kicad-pcb.org/display/KICAD/Frequently+Asked+Questions was removed.

instead of FAQ link, what about putting the formal documentation link here ?
like this.
<pre>
[[kicad-documentation-on-the-web]]
=== KiCad documentation on the Web

Latest KiCad documentations are available in multi-language on the Web.
http://kicad-pcb.org/help/documentation/
</pre>

**Comment by nickoe** [comment]
Yeah, that is probably better since we have not yet ported the old FAQ to the new site. Please go ahead an make a pull request.

**Comment by kinichiro** [comment]
Merged, thanks.
