### ISSUE TITLE
Installed HTML help contains images for other languages

### ISSUE THREAD

**Issue by onitake** [KiCad/kicad-doc#170]
I'm not sure if this is related to #168, but images for other languages "bleed" into each HTML build result.

For example, if I build the English documentation and `make install` it, I will get a `/usr/share/doc/kicad/help/en` with a subdirectory `images`. Inside, there are the images for the English HTML files, but also `it` and `ja` subdirectories. These contain images for the respective languages.

Is this intended, or a result of my parallel build (with `make -j4`)?

**Comment by nickoe** [comment]
This is indeed a bug. I appeared after I changed it to install like kicad wanted the help files. I intend to fix this.

**Comment by BrianSidebotham** [comment]
I'm not sure this is new. I think this has always been the case although not desirable.

At the moment it's one of the things that adds to the long packaging time

**Comment by onitake** [comment]
It's also strange that some languages are not included. I get en, it, pl and ja subfolders for each language, but never fr or nl.

**Comment by nickoe** [comment]
Mmm, it seems that https://github.com/KiCad/kicad-doc/commit/f52c2c89c274d079062fe7a6e8234459e099a193 does not fix this issue at all.

**Comment by ciampix** [comment]
Is this bug still present? If not, may I close this? If yes, how can I reproduce it?

**Comment by nickoe** [comment]
@ciampix I don't remember if I really managed to fix this properly. It is solely a matter of testing it.

**Comment by ciampix** [comment]
ok
cmake ..
make make getting_started_in_kicad_html_en
... so long so good...
sudo make install getting_started_in_kicad_html_en
install _ALL_ the images... apparently the bug is still there...
