### ISSUE TITLE
GSIK: Section 1; cvpcb no-longer standalone 

### ISSUE THREAD

**Issue by bobc** [KiCad/kicad-doc#224]
cvpcb is no longer a standalone tool. I suggest that it's function "footprint selector" be added to eeschema row, and cvpcb row removed.

**Comment by kinichiro** [comment]
absolutely.
cvpcb is no more a standalone program,
but it is still described as one program in some documents
since it is transition period of changing KiCad.
not only that, it has its own independent reference manual, still.
it needs more time to fix these issues.

**Comment by bobc** [comment]
Surely we should change those other documents as well then :puzzled:

**Comment by evanshultz** [comment]
Six months later it appears there's no change. I'm happy to do this and will start on it shortly.

**Comment by evanshultz** [comment]
The patches for GSIK (and also KiCad) are merged. @ciampix you may close this issue if you like, as the purpose of this issue is addressed and I'll merge the actual CvPcb documentation into Eeschema when I get there.

**Comment by ciampix** [comment]
yes of course, thanks!
