### ISSUE TITLE
GSIK: German translation is WIP

### ISSUE THREAD

**Issue by tijuca** [KiCad/kicad-doc#239]
Hello,

I just want to prevent some double work. I've started to work on the German translation for getting_started_in_kicad. But I will need a few more days. Thanks.

**Comment by ciampix** [comment]
My 2 euro cent suggestion: just commit your work, even if small. So you can ask for someone to revise it on-line reading from the multilingual compilation results...

**Comment by tijuca** [comment]
Well, the translation isn't the difficult part. this is almost done. But the must boring work is to collect the respecting German menu entrys. I found there some more missed or better to translate strings in KiCad itself. After I synced the de/kicad.po to the current upstream base there was even more new strings to translate.
Also this part is mostly finished, so I will send two pull requests (one for kicad-i18n and the other for kicad-doc) shortly, hopefully yet this year. :-)

**Comment by ciampix** [comment]
Ok, then may I close this PR?

**Comment by tijuca** [comment]
You mean (this) Issue?
I'd like to let it open until I finished my work for the pull request so everybody else is able to see there is something going on.

**Comment by ciampix** [comment]
ok
