### ISSUE TITLE
Confusion between hierachical pins and labels in Eeschema

### ISSUE THREAD

**Issue by MarcusFecit** [KiCad/kicad-doc#244]
Section 6.6, "Connections - hierarchical pins", Manual placement.
This section is supposed to show the placement of a hierarchical pin, but the image and the attributes description are for the properties of a hierarchical label.

**Comment by evanshultz** [comment]
Agreed. I submitted a pull request for eeschema_hierarchical_schematics.adoc, with the screenshot below replacing images/eeschema_hierarchical_label.png:
<img width="202" alt="eeschema_hierarchical_pin" src="https://cloud.githubusercontent.com/assets/1936989/16013565/c6a21788-3142-11e6-9ddf-bcddcc083afa.png">

**Comment by evanshultz** [comment]
I believe this issue can now be closed.

**Comment by ciampix** [comment]
Yes, surely.
