### ISSUE TITLE
Getting error during install

### ISSUE THREAD

**Issue by keruseykaryu** [KiCad/kicad-doc#306]
I'm getting error during full KiCad build with Linux Mint Rosa:

    Scanning dependencies of target pl_editor_translate_en
    Built target pl_editor_translate_en
    Scanning dependencies of target pl_editor_html_en
    Built target pl_editor_html_en
    Scanning dependencies of target pl_editor_translate_es
    Built target pl_editor_translate_es
    Scanning dependencies of target pl_editor_html_es
    asciidoc: ERROR: pl_editor.adoc: line 640: [tabledef-default] missing closing delimiter
    make[2]: *** [src/pl_editor/CMakeFiles/pl_editor_html_es] Error 1
    make[1]: *** [src/pl_editor/CMakeFiles/pl_editor_html_es.dir/all] Error 2
    make: *** [all] Error 2

**Comment by nickoe** [comment]
Same does http://ci.kicad-pcb.org/job/any-kicad-doc-head/203/console

**Comment by nickoe** [comment]
I think it is working now.

**Comment by ciampix** [comment]
IIRC previously it was possible to start an automatic compiling test with Jenkins simply writing a message containing "retest this please". Now it does not work anymore. Does anyone know how to re-enable it? Just tell me how to do it... I want to learn...
