### ISSUE TITLE
KiCad

### ISSUE THREAD

**Issue by LarryJoy** [KiCad/kicad-doc#342]
[KiCad.pdf](https://github.com/KiCad/kicad-doc/files/222969/KiCad.pdf)

KiCAD April 9, 2016
Document comments and feedback
- [x] 2.2, 1 st paragraph, 2 nd line, “If an other default...” Should be “If another default...”

ok fixed by @Caerbannog 

- [x] Page 13, bottom of page, “Project from Template”, 2 nd line, near the end, “...will load that templates info.html...” Should be “...will load that template's info.html...”

ok

- [x] Page 14, last figure at bottom of page, “Templates path”. Should be “Template's path” unless you're talking about multiple templates, in which case I think it would be “templates' path”.

ok fixed by @Caerbannog

**Comment by Caerbannog** [comment]
It will be easier next time if you just paste your text here instead of including a pdf :smiley:
