### ISSUE TITLE
Eeschema

### ISSUE THREAD

**Issue by LarryJoy** [KiCad/kicad-doc#343]

**Comment by LarryJoy** [comment]
[Eeschema.pdf](https://github.com/KiCad/kicad-doc/files/223005/Eeschema.pdf)

**Comment by evanshultz** [comment]
"Bill of Materials" is widely understood. Same with symbols.

For other issues, @ciampix or I have done them. This was great feedback and I nominate closing.

**Comment by evanshultz** [comment]
@ciampix Can this issue be closed? It appears everything has been implemented.

**Comment by kinichiro** [comment]
I checked all the issues above with master branch document, and it is OK.
There are 7 unchecked still, but we won't fix these since these can't fix on documentation.
I would like to close this issue in this weekend if there is no objection :-)

**Comment by nickoe** [comment]
No objection from here.

**Comment by LarryJoy** [comment]
Yes, okay to close.Larry Joy

**Comment by kinichiro** [comment]
Thanks for confirmation message. This is closed.
