### ISSUE TITLE
Pcbnew: Sections 10.9 and 10.10

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-doc#372]
A few issues here:

1. There appears to be a toolbar icon missing in the first sentence of 10.9.1 ("...using the button ."). It should be the "Add filled zones" icon.

2. Both dialog screenshots use French layer names, which isn't an issue per se but I assume it should be English like other screenshots I see.

3. The screenshot in 10.9.1 is an old dialog and not representative of 4.0.2 stable.

**Comment by ciampix** [comment]
Thanks for the heads-up. If you are so kind to deliver the missing / right icon and screenshot or please be patient and I will do it...

**Comment by evanshultz** [comment]
I don't have write access, but the new images are attached and need to go in kicad-doc/src/pcbnew/images/.
<img width="213" alt="pcbnew_technical_layer_zone_dialog" src="https://cloud.githubusercontent.com/assets/1936989/15994567/35217522-30bd-11e6-95f4-230cc186cbea.png">
<img width="379" alt="pcbnew_keepout_area_properties" src="https://cloud.githubusercontent.com/assets/1936989/15994568/35222706-30bd-11e6-9d43-a879cd18417c.png">
