### ISSUE TITLE
LibEdit - "Complements"? Not "Components" or something else?

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-doc#387]
Is there a typo for the 12th Eeschema chapter name? See https://github.com/KiCad/kicad-doc/blob/master/src/eeschema/eeschema.adoc and https://github.com/KiCad/kicad-doc/blob/master/src/eeschema/eeschema_libedit_complements.adoc. Maybe I'm just not understanding, but the word "complement" doesn't seem to fit here.

**Comment by ciampix** [comment]
Thanks for this, I am seeing about it. Commit arriving in a minute.

**Comment by ciampix** [comment]
Commit arrived before the comment! :-)
