### ISSUE TITLE
OS X support is experimental?

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-doc#400]
https://github.com/KiCad/kicad-doc/blob/master/src/kicad/kicad.adoc mentions this, but the three OS options seem to be mentioned with equal footing on the website and elsewhere I've seen. Is this true, or legacy text that can be removed?

**Comment by nickoe** [comment]
@evanshultz Thank you for spending effort in keeping the docs recent!

Yes, I think we can proudly say that OS X is supported by now. There are multiple developers on OS X and it seems that it is on par with the other platforms since kicad 4.0.0.

**Comment by ciampix** [comment]
Thank you @nickoe, I was just waiting a dev word on this. Ok @evanshultz please go on and thank you for this!

**Comment by evanshultz** [comment]
And there we have it!
