### ISSUE TITLE
cvpcb 

### ISSUE THREAD

**Issue by chinthan12** [KiCad/kicad-doc#496]
in my pc the cvpcp is not working its showing that not responding

**Comment by keruseykaryu** [comment]
This is not a right place to discuss about CvPcb issues. Please search the KiCad user forum https://forum.kicad.info/search?q=cvpcb and you will find an answer.

**Comment by chinthan12** [comment]
Thanks

**Comment by ciampix** [comment]
Thanks @keruseykaryu !
