### ISSUE TITLE
Offering Fix for Debian Build

### ISSUE THREAD

**Issue by codemonkeyrawks** [KiCad/kicad-doc#643]
Attached is supporting documentation for installing KiCad on Debian. I had to rename the doc to get this to attach (lines: 123 - 138).

[Getting Started in KiCad](https://github.com/KiCad/kicad-doc/files/2722395/getting_started_in_kicad.txt)

**Comment by codemonkeyrawks** [comment]
__________________________________________________

Under Debian, the easiest way to install backports build of KiCad is:
__________________________________________________

# Set up Debian Backports
echo -e "
# stretch-backports
deb http://ftp.us.debian.org/debian/ stretch-backports main contrib non-free 
deb-src http://ftp.us.debian.org/debian/ stretch-backports main contrib non-free
" | sudo tee -a /etc/apt/sources.list > /dev/null

# Run an Update: Install KiCad
sudo apt-get update
sudo apt-get install -t stretch-backports kicad
__________________________________________________

**Comment by ciampix** [comment]
I'm seeing to it now, please be patience, thanks!

**Comment by codemonkeyrawks** [comment]
Thanks @ciampix .
