### ISSUE TITLE
Getting Started - Wrong Symbol for PIC12C508A-ISN

### ISSUE THREAD

**Issue by fdamstra** [KiCad/kicad-doc#644]
The [Getting Started Documentation](http://docs.kicad-pcb.org/stable/en/getting_started_in_kicad.html) says the PIC12C508A-ISN should look like this:
![PIC12C508A-ISN](http://docs.kicad-pcb.org/stable/en/images/gsik_tutorial1_010.png)

But the PIC12C508A-ISN added from the library looks entirely different, with 1 VDD on the top, one VSS on the bottom, and 3 GP pins on the left and right.

This breaks the rest of getting started.

Platform:
Windows 10

To reproduce:
Install 5.0.2 from scratch. Try to go through the "Getting started" tutorial.

**Comment by ciampix** [comment]
Good point (and thanks for pointing it out) so why not provide a PL with a patch? ;-)

**Comment by EeliK** [comment]
It has been fixed in HEAD, I have updated the pictures.

**Comment by tijuca** [comment]
So this issue could be closed?

**Comment by nickoe** [comment]
Okay.
