### ISSUE TITLE
The definition of "fuzzy"

### ISSUE THREAD

**Issue by needfulthing** [KiCad/kicad-doc#651]
I found that a lot of sections are marked as fuzzy because they are not exactly translated word by word. The problem with translations from English to other languages is that English is able to express a lot with very few words. This might lead to confusion in other languages like German, so it should be possible to describe the sense with other words without getting the section marked as fuzzy. I'm currently creating a new German translation for the Getting Started guide and I remove all the fuzzy tags where I'm sure the translation is now sufficiently good, which means it transports the information of the original section as close as possible to the English wording, but maybe not in the exact words if this is not the ideal solution. It would be frustrating to find all these sections marked as fuzzy again by someone else later on.

**Comment by ciampix** [comment]
No. The "fuzzy" string simply marks that the actual translation was made to an old copy of the English string or sentence. That has nothing to do with the meaning. Sometimes the translation change was trivial (e. g. for a typo), sometimes the original string changed substantially. The "fuzzy" string marks that the translator should review the translation. In the first case he/she can just "unfuzzy" the translation but it is up to the translator to decide about it. If you want to know more about it, read about the .po files in the gettext package documentation (the reference) or in the poedit manual.
