### ISSUE TITLE
On Chinese Simplified  (zh_CN) and Chinese Traditional  (zh_TW)

### ISSUE THREAD

**Issue by taotieren** [KiCad/kicad-doc#672]
There are Chinese Simplified (zh_CN) and Chinese Traditional (zh_TW) in Chinese. I use Chinese Simplified  (zh_CN). Chinese translation in kicad-doc is also using Chinese Simplified  (zh_CN). Can zh.po be updated to zh_CN.po?

**Comment by taotieren** [comment]
Simplified Chinese(zh_CN) and Traditional Chinese(zh_TW) have different vocabulary and usage.

**Comment by ciampix** [comment]
Cmake scripts have to be updated to work with aa_BB form .po and more generally i18n files (addendum and xml files for asciidoc)
