### ISSUE TITLE
Floating menu on top of the documentation page

### ISSUE THREAD

**Issue by kr15h** [KiCad/kicad-doc#673]
Hi! Is this normal (the floating table of contents)? See screenshot below.

<img width="1440" alt="screenshot 2019-02-26 at 14 11 31" src="https://user-images.githubusercontent.com/817241/53411925-8b074100-39d0-11e9-9f20-199416dbbc41.png">

**Comment by nickoe** [comment]
https://github.com/KiCad/kicad-doc-website/issues/3
