### ISSUE TITLE
Use the same logo as website on PDF?

### ISSUE THREAD

**Issue by marekr** [KiCad/kicad-doc#685]
So right now the generated PDF has a goldish form of the logo in a different font.

Any reason it's not the "main" blue and white logo? 

![image](https://user-images.githubusercontent.com/1838013/53890547-69bcdb00-3ff6-11e9-89c5-b5424f0b4fc5.png)

vs

![image](https://user-images.githubusercontent.com/1838013/53890556-6cb7cb80-3ff6-11e9-9f4b-6c1077efd0ba.png)

which is used on the website(s) and even the application

**Comment by stambaughw** [comment]
We should be using the new KiCad logo image everywhere in place of the old logo.

**Comment by ciampix** [comment]
Sorry I'm a bit "new"... which one is the "new logo"?

**Comment by stambaughw** [comment]
@ciampix the blue logo.

**Comment by ciampix** [comment]
Ok so it is wrong even in the program icon and the about window! I suggest to fix it in the next upcoming 6 version though... it's too late for this change in the 5.2 I am afraid...

**Comment by alfrede** [comment]
After all my mistakes i do, i think for version 6 we should rewrite the "README for doc authors".

I will write down my experiences.

**Comment by ciampix** [comment]
@alfrede yours is a very good idea™

**Comment by ciampix** [comment]
Even in the bug tracker the icon is the old one...

**Comment by nickoe** [comment]
@stambaughw I don't have access to edit it on the launchpad page, but I have attached a 400px version for your convince.

I suggest to use the Ki for the square icons.
![kicad_400px](https://user-images.githubusercontent.com/352202/53980744-60746100-4111-11e9-9f8c-17ca6b50efd8.png)

**Comment by nickoe** [comment]
@marekr I guess the main reason is that there was a time someone wrote some docs, this in a time where people were inspired by libreoffice designs... and then no one dared to change it. I think the blue KiCad logo is widely used and recognized, so we should of course use it for the title page of the docs. I have had the intention to change it for a long time, but never got around to it.

**Comment by marekr** [comment]
@nickoe Yea that's fine. I was just bringing it up. It looks like it should be changed for 5.1 just fine? It doesn't affect translations and it's just a logo.png in each doc folder.

**Comment by nickoe** [comment]
Yeah, xeel free to pr it

**Comment by nickoe** [comment]
Woopsie, fixed in 5ed4c47
