### ISSUE TITLE
Why is there no Chinese Help Manual in Kicad 5.1.0？

### ISSUE THREAD

**Issue by taotieren** [KiCad/kicad-doc#701]
Why is there no Chinese Help Manual in Kicad 5.1.0？

**Comment by ciampix** [comment]
I see it here... http://docs.kicad-pcb.org/5.1.0/zh/
Where are you looking at?

**Comment by taotieren** [comment]
I mean there is no Chinese manual in the packaged installation package (C:\Program Files\KiCad\share\doc\kicad\help),No zh folder

**Comment by nickoe** [comment]
I assume you are only talking about the windows installer. This section needs to be updated:

https://github.com/KiCad/kicad-winbuilder/blob/d0546e9f0fa7925d4a81b0df91430bd6b559f04b/nsis/install.nsi#L385

**Comment by taotieren** [comment]
@nickoe Thanks

**Comment by taotieren** [comment]
What about the help manual on kicad under Linux and MacOS?

**Comment by nickoe** [comment]
You need to check if they use implicit or explicit packaging rules. I saw that the debian package did package it. I am not sure about macos or the ubuntu ppa.

**Comment by taotieren** [comment]
@nickoe OK, I will check if they are packaged, is there a packaged warehouse link? Packing under Windows I have added a Chinese installation profile and so on.

**Comment by nickoe** [comment]
@taotieren Thank you. I added a comment on a minor issue. If you address it I can merge it.

**Comment by nickoe** [comment]
@taotieren I think this is the source for the PPA packges, https://git.launchpad.net/~js-reynaud/+git/kicad-doc-pkg/tree/debian?id=5.1

@jsreynaud It does not look like zh is included.

**Comment by jsreynaud** [comment]
Let me add it...

**Comment by taotieren** [comment]
@nickoe  https://github.com/KiCad/kicad-winbuilder/pull/78

**Comment by taotieren** [comment]
@jsreynaud @nickoe  @ciampix Thanks！
