### ISSUE TITLE
"Python Scripting Reference" link broken in pcbnew docs

### ISSUE THREAD

**Issue by gabebuckmaster** [KiCad/kicad-doc#710]
In the online version of the Pcbnew docs (http://docs.kicad-pcb.org/5.1.0/en/pcbnew/pcbnew.html), the link "Python Scripting Reference" under the heading KiCad Scripting Reference gives me a 404 error. It currently points to http://docs.kicad-pcb.org/doxygen-python/namespaces.html.

**Comment by nickoe** [comment]
This is known https://github.com/KiCad/kicad-doc-website/issues/14

**Comment by gabebuckmaster** [comment]
Ahh, thanks. I'll assume there's a good reason the link hasn't been updated to point to the documentation referenced in KiCad/kicad-doc-website#14.
