### ISSUE TITLE
KiCad Library Convention part of this repo?

### ISSUE THREAD

**Issue by yankee14** [KiCad/kicad-doc#725]
I was going to submit a PR for some typos I found at http://kicad-pcb.org/libraries/klc/. Is that under version control in this repository, or in another one somewhere else? I can't seem to find it.

**Comment by antoniovazquezblanco** [comment]
KLC is at https://github.com/KiCad/kicad-website AFAIK

**Comment by yankee14** [comment]
Thank you!
