### ISSUE TITLE
Problem with GND connections

### ISSUE THREAD

**Issue by Peter-Rtd** [KiCad/kicad-doc#740]
KICAD

I have started to use KICAD (for the first time) for a PCB design, but I have a problem. 

After entering the design into Eeschema and running the "electrical riules check" I get the message 
"Pin connected to other pins, but not driven by any other pin. 
@(location) Pin 1 of component #PWR#083 is not driven (Net 1)" 

(Note that NET 1 is GND).

If I go into the schematic and re-draw the area in question (to an apparently exact reproduction) and re-run the rules check
I get a similar message, but describing a problem with another GND connection. If I "correct" that area of the drawing the 
problem moves to yet another pin. In one series of attempts to clear the issue it seems that a "loop" was formed with the 
problem moving round a number of pins.

When I checked the netlist from the design in the case of the problem with #PWR083 I found that the decoupling capacitor 
concerned was, in fact, included in the GND netlist. I have continued with the design, but I am concerned that I may have done something wrong. Please advise.

Regards

**Comment by poeschlr** [comment]
This is not the place to ask questions but to report issues with the docuementation. For the future please head over to https://forum.kicad.info/ for support.

You might want to read: https://forum.kicad.info/t/errtype-3-pin-connected-to-some-others-pins-but-no-pin-to-drive-it/10946/
