### ISSUE TITLE
Move to kicad/kicad-doc

### ISSUE THREAD

**Issue by Caerbannog** [KiCad/kicad-doc#92]
Should new pushes go to kicad/kicad-doc?
(it seems to lag behind at the moment)

Should the issues be transferred too?
It seems possible: https://help.github.com/articles/transferring-a-repository/

**Comment by nickoe** [comment]
I don't know, maybe it is @stambaughw trying to move it over. Maybe we will see something on the list shortly.

**Comment by stambaughw** [comment]
It wasn't me.  I see someone already transferred (or maybe they just
cloned which wasn't the correct way to do this) the kicad-doc repo to
github:\\KiCad.

**Comment by kinichiro** [comment]
Is this a formal upstream for kicad-doc activities or not ?
Kicad/kicad-doc seems stop since Jun-25th.
Which repo to align our translation tasks ?

**Comment by nickoe** [comment]
For now use this one (ciampix).

**Comment by ciampix** [comment]
Repo transfered.
